#! /bin/sh

#get some toosl to build projects
sudo apt-get update
sudo apt-get install build-essential libncurses5 libncurses5-dev mercurial git libpython2.7 libpython3.2

# checkout, compile, and install the vim project
hg clone https://vim.googlecode.com/hg/ vim
cd vim/src
make distclean
make clean
./configure --enable-pythoninterp --enable-python3interp --enable-cscope --with-features=big --with-compiledby=bhvr
make
sudo make install
mkdir ~/.vim

#install colours for vim
mkdir ~/.vim/colors
wget -O ~/.vim/colors/inkpot.vim https://raw.github.com/ciaranm/inkpot/master/colors/inkpot.vim
echo '
"turn on syntax highlighting and colours
syntax on
colorscheme inkpot

"mintty colour settings
let &t_Co=256 
let &t_AF="\e[38;5;%dm" 
let &t_AB="\e[48;5;%dm" 
' >> ~/.vimrc

echo "
\" Vim color file - inkpot
\" Generated by http://bytefluent.com/vivify 2012-02-07
set background=dark
if version > 580
	hi clear
	if exists(\"syntax_on\")
		syntax reset
	endif
endif

let g:colors_name = \"inkpot\"

hi IncSearch guifg=#303030 guibg=#cd8b60 guisp=#cd8b60 gui=none ctermfg=236 ctermbg=173 cterm=none
hi WildMenu guifg=#eeeeee guibg=#6e6eaf guisp=#6e6eaf gui=none ctermfg=255 ctermbg=61 cterm=none
hi SignColumn guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi SpecialComment guifg=#c080d0 guibg=none guisp=none gui=none ctermfg=176 ctermbg=none cterm=none
hi Typedef guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi Title guifg=#af4f4b guibg=none guisp=none gui=none ctermfg=131 ctermbg=none cterm=none
hi Folded guifg=#cfcfcd guibg=#4b208f guisp=#4b208f gui=none ctermfg=252 ctermbg=54 cterm=none
hi PreCondit guifg=#409090 guibg=none guisp=none gui=none ctermfg=66 ctermbg=none cterm=none
hi Include guifg=#409090 guibg=none guisp=none gui=none ctermfg=66 ctermbg=none cterm=none
hi TabLineSel guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi StatusLineNC guifg=#b9b9b9 guibg=#3e3e5e guisp=#3e3e5e gui=none ctermfg=250 ctermbg=60 cterm=none
hi CTagsMember guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi NonText guifg=#8b8bcd guibg=none guisp=none gui=none ctermfg=104 ctermbg=none cterm=none
hi CTagsGlobalConstant guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi DiffText guifg=#ffffcd guibg=#4a2a4a guisp=#4a2a4a gui=none ctermfg=230 ctermbg=239 cterm=none
hi ErrorMsg guifg=#ffffff guibg=#ce4e4e guisp=#ce4e4e gui=none ctermfg=15 ctermbg=167 cterm=none
hi Ignore guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Debug guifg=#c080d0 guibg=none guisp=none gui=none ctermfg=176 ctermbg=none cterm=none
hi PMenuSbar guifg=#eeeeee guibg=#6e6eaf guisp=#6e6eaf gui=none ctermfg=255 ctermbg=61 cterm=none
hi Identifier guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi SpecialChar guifg=#c080d0 guibg=#404040 guisp=#404040 gui=none ctermfg=176 ctermbg=238 cterm=none
hi Conditional guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi StorageClass guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi Todo guifg=#303030 guibg=#d0a060 guisp=#d0a060 gui=none ctermfg=236 ctermbg=179 cterm=none
hi Special guifg=#c080d0 guibg=none guisp=none gui=none ctermfg=176 ctermbg=none cterm=none
hi LineNr guifg=#8b8bcd guibg=#2e2e2e guisp=#2e2e2e gui=none ctermfg=104 ctermbg=236 cterm=none
hi StatusLine guifg=#b9b9b9 guibg=#3e3e5e guisp=#3e3e5e gui=none ctermfg=250 ctermbg=60 cterm=none
hi Normal guifg=#cfbfad guibg=#1e1e27 guisp=#1e1e27 gui=none ctermfg=187 ctermbg=235 cterm=none
hi Label guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi CTagsImport guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi PMenuSel guifg=#eeeeee guibg=#2e2e3f guisp=#2e2e3f gui=none ctermfg=255 ctermbg=237 cterm=none
hi Search guifg=#303030 guibg=#cd8b60 guisp=#cd8b60 gui=none ctermfg=236 ctermbg=173 cterm=none
hi CTagsGlobalVariable guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Delimiter guifg=#c080d0 guibg=none guisp=none gui=none ctermfg=176 ctermbg=none cterm=none
hi Statement guifg=#808bed guibg=none guisp=none gui=none ctermfg=105 ctermbg=none cterm=none
hi SpellRare guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi EnumerationValue guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Comment guifg=#cd8b00 guibg=none guisp=none gui=none ctermfg=172 ctermbg=none cterm=none
hi Character guifg=#ffcd8b guibg=none guisp=none gui=none ctermfg=222 ctermbg=none cterm=none
hi Float guifg=#f0ad6d guibg=none guisp=none gui=none ctermfg=215 ctermbg=none cterm=none
hi Number guifg=#f0ad6d guibg=none guisp=none gui=none ctermfg=215 ctermbg=none cterm=none
hi Boolean guifg=#808bed guibg=none guisp=none gui=none ctermfg=105 ctermbg=none cterm=none
hi Operator guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi CursorLine guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Union guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi TabLineFill guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Question guifg=#ffcd00 guibg=none guisp=none gui=none ctermfg=220 ctermbg=none cterm=none
hi WarningMsg guifg=#ffffff guibg=#ce8e4e guisp=#ce8e4e gui=none ctermfg=15 ctermbg=173 cterm=none
hi VisualNOS guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi DiffDelete guifg=#ffffcd guibg=#6d3030 guisp=#6d3030 gui=none ctermfg=230 ctermbg=95 cterm=none
hi ModeMsg guifg=#7e7eae guibg=none guisp=none gui=none ctermfg=103 ctermbg=none cterm=none
hi CursorColumn guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Define guifg=#409090 guibg=none guisp=none gui=none ctermfg=66 ctermbg=none cterm=none
hi Function guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi FoldColumn guifg=#8b8bcd guibg=#2e2e2e guisp=#2e2e2e gui=none ctermfg=104 ctermbg=236 cterm=none
hi PreProc guifg=#409090 guibg=none guisp=none gui=none ctermfg=66 ctermbg=none cterm=none
hi EnumerationName guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Visual guifg=#eeeeee guibg=#4e4e8f guisp=#4e4e8f gui=none ctermfg=255 ctermbg=60 cterm=none
hi MoreMsg guifg=#7e7eae guibg=none guisp=none gui=none ctermfg=103 ctermbg=none cterm=none
hi SpellCap guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi VertSplit guifg=#b9b9b9 guibg=#3e3e5e guisp=#3e3e5e gui=none ctermfg=250 ctermbg=60 cterm=none
hi Exception guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi Keyword guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi Type guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi DiffChange guifg=#ffffcd guibg=#306b8f guisp=#306b8f gui=none ctermfg=230 ctermbg=24 cterm=none
hi Cursor guifg=#404040 guibg=#8b8bff guisp=#8b8bff gui=none ctermfg=238 ctermbg=105 cterm=none
hi SpellLocal guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Error guifg=#ffffff guibg=#6e2e2e guisp=#6e2e2e gui=none ctermfg=15 ctermbg=95 cterm=none
hi PMenu guifg=#eeeeee guibg=#4e4e8f guisp=#4e4e8f gui=none ctermfg=255 ctermbg=60 cterm=none
hi SpecialKey guifg=#ab60ed guibg=none guisp=none gui=none ctermfg=135 ctermbg=none cterm=none
hi Constant guifg=#ffcd8b guibg=none guisp=none gui=none ctermfg=222 ctermbg=none cterm=none
hi DefinedName guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Tag guifg=#c080d0 guibg=none guisp=none gui=none ctermfg=176 ctermbg=none cterm=none
hi String guifg=#ffcd8b guibg=#404040 guisp=#404040 gui=none ctermfg=222 ctermbg=238 cterm=none
hi PMenuThumb guifg=#eeeeee guibg=#6e6eaf guisp=#6e6eaf gui=none ctermfg=255 ctermbg=61 cterm=none
hi MatchParen guifg=#404040 guibg=#8fff8b guisp=#8fff8b gui=none ctermfg=238 ctermbg=120 cterm=none
hi LocalVariable guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Repeat guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi SpellBad guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi CTagsClass guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi Directory guifg=#00ff8b guibg=none guisp=none gui=none ctermfg=48 ctermbg=none cterm=none
hi Structure guifg=#ff8bff guibg=none guisp=none gui=none ctermfg=213 ctermbg=none cterm=none
hi Macro guifg=#409090 guibg=none guisp=none gui=none ctermfg=66 ctermbg=none cterm=none
hi Underlined guifg=#df9f2d guibg=none guisp=none gui=none ctermfg=172 ctermbg=none cterm=none
hi DiffAdd guifg=#ffffcd guibg=#306d30 guisp=#306d30 gui=none ctermfg=230 ctermbg=65 cterm=none
hi TabLine guifg=none guibg=none guisp=none gui=none ctermfg=none ctermbg=none cterm=none
hi mbenormal guifg=#cfbfad guibg=#2e2e3f guisp=#2e2e3f gui=none ctermfg=187 ctermbg=237 cterm=none
hi perlspecialstring guifg=#c080d0 guibg=#404040 guisp=#404040 gui=none ctermfg=176 ctermbg=238 cterm=none
hi doxygenspecial guifg=#fdd090 guibg=none guisp=none gui=none ctermfg=222 ctermbg=none cterm=none
hi mbechanged guifg=#eeeeee guibg=#2e2e3f guisp=#2e2e3f gui=none ctermfg=255 ctermbg=237 cterm=none
hi mbevisiblechanged guifg=#eeeeee guibg=#4e4e8f guisp=#4e4e8f gui=none ctermfg=255 ctermbg=60 cterm=none
hi doxygenparam guifg=#fdd090 guibg=none guisp=none gui=none ctermfg=222 ctermbg=none cterm=none
hi doxygensmallspecial guifg=#fdd090 guibg=none guisp=none gui=none ctermfg=222 ctermbg=none cterm=none
hi doxygenprev guifg=#fdd090 guibg=none guisp=none gui=none ctermfg=222 ctermbg=none cterm=none
hi perlspecialmatch guifg=#c080d0 guibg=#404040 guisp=#404040 gui=none ctermfg=176 ctermbg=238 cterm=none
hi cformat guifg=#c080d0 guibg=#404040 guisp=#404040 gui=none ctermfg=176 ctermbg=238 cterm=none
hi lcursor guifg=#404040 guibg=#8fff8b guisp=#8fff8b gui=none ctermfg=238 ctermbg=120 cterm=none
hi cursorim guifg=#404040 guibg=#8b8bff guisp=#8b8bff gui=none ctermfg=238 ctermbg=105 cterm=none
hi doxygenspecialmultilinedesc guifg=#ad600b guibg=none guisp=none gui=none ctermfg=130 ctermbg=none cterm=none
hi taglisttagname guifg=#808bed guibg=none guisp=none gui=none ctermfg=105 ctermbg=none cterm=none
hi doxygenbrief guifg=#fdab60 guibg=none guisp=none gui=none ctermfg=215 ctermbg=none cterm=none
hi mbevisiblenormal guifg=#cfcfcd guibg=#4e4e8f guisp=#4e4e8f gui=none ctermfg=252 ctermbg=60 cterm=none
hi user2 guifg=#7070a0 guibg=#3e3e5e guisp=#3e3e5e gui=none ctermfg=103 ctermbg=60 cterm=none
hi user1 guifg=#00ff8b guibg=#3e3e5e guisp=#3e3e5e gui=none ctermfg=48 ctermbg=60 cterm=none
hi doxygenspecialonelinedesc guifg=#ad600b guibg=none guisp=none gui=none ctermfg=130 ctermbg=none cterm=none
hi doxygencomment guifg=#ad7b20 guibg=none guisp=none gui=none ctermfg=130 ctermbg=none cterm=none
hi cspecialcharacter guifg=#c080d0 guibg=#404040 guisp=#404040 gui=none ctermfg=176 ctermbg=238 cterm=none

" >> ~/.vim/colors/inkpot.vim

#add other settings to the vim.rc file
echo "
\"maps accidental key strokes on commands to their actual commands
:command Q :q
:command Qa :qa
:command QA :qa
:command Xa :xa
:command XA :xa
:command W :w
:command Wa :wa
:command WA :wa

\"using improved vi
set nocompatible

\"makes sure the backspace key is set to work on various terminals
set backspace=2

\"allows to hide unsaved buffers
set hidden

\"folding settings
\"Enable indent folding
set foldenable
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1

\"set line numbers
set number


\"maps auto complete to ctrl+space
inoremap <expr> <C-Space> pumvisible() \|\| &omnifunc == '' ?
\\ \"\\<lt>C-n>\" :
\\ \"\\<lt>C-x>\\<lt>C-o><c-r>=pumvisible() ?\" .
\\ \"\\\"\\\\<lt>c-n>\\\\<lt>c-p>\\\\<lt>c-n>\\\" :\" .
\\ \"\\\" \\\\<lt>bs>\\\\<lt>C-n>\\\"\\<CR>\"
imap <C-@> <C-Space>

\"Turn on incremental search with ignore case (except explicit caps)
set incsearch
set ignorecase
set smartcase

\"Have 3 lines of offset (or buffer) when scrolling
set scrolloff=3

\"Set line numbering to take up 5 spaces
set numberwidth=5 \"Highlight current line
set cursorline

\"Turn on spell checking with English dictionary
set spell
set spelllang=en
set spellsuggest=9 \"show only 9 suggestions for misspelled words

\"change the highlighting for spell checks
hi clear SpellBad
hi SpellBad cterm=underline

\"set agreedupon indenting format
set expandtab
set ts=2
set shiftwidth=2
set smartindent


\"underlines the cursor line
hi CursorLine cterm=underline

\"underline the current tab
hi TabLineSel cterm=underline


\"vundle setup
filetype off                   \" required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

\" let Vundle manage Vundle
\" required!
Bundle 'gmarik/vundle'

\" My Bundles here:
\"
\" original repos on github
Bundle 'Valloric/YouCompleteMe'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/syntastic'
Bundle 'majutsushi/tagbar'
Bundle 'tpope/vim-dispatch'
Bundle 'szw/vim-tags'
Bundle 'Lokaltog/vim-powerline'

filetype plugin indent on     \" required!
\"
\" Brief help
\" :BundleList          - list configured bundles
\" :BundleInstall(!)    - install(update) bundles
\" :BundleSearch(!) foo - search(or refresh cache first) for foo
\" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
\"
\" see :h vundle for more details or wiki for FAQ
\" NOTE: comments after Bundle command are not allowed..


\" vim tabs key binding
nmap <F8> :TagbarToggle<CR>

\" vim-tags configuration
let g:vim_tags_auto_generate = 1
let g:vim_tags_project_tags_command = \"ctags -R {OPTIONS} {DIRECTORY} 2>/dev/null\"
let g:vim_tags_use_vim_dispatch = 1
let g:vim_tags_ignore_files = ['.gitignore', '.hgignore']
let g:vim_tags_ignore_file_comment_pattern = '^[#\"]'
let g:vim_tags_directories = []
let g:vim_tags_main_file = 'vim_tags'
let g:vim_tags_extension = '.tags'

\" remap ctr-] to open the tag in a new tab
:nnoremap <C-]> <C-w><C-]><C-w>T
" >> ~/.vimrc


#add vundle to manage vim bundles
mkdir ~/.vim/bundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

#add this php debugger to debug php when it has xdebug enabled
wget -O /var/tmp/debugger.tar.gz http://www.vim.org/scripts/download_script.php?src_id=9793
tar -zxvf /var/tmp/debugger.tar.gz -C ~/.vim/
rm /var/tmp/debugger.tar.gz
